[project]
name = "ai-coach-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rajamanickam R", email = "rajamanickam.rp@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[tool.pytest.ini_options]
pythonpath = ["."]

[project.scripts]
ai-coach-rag = "ai_coach_rag:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
